name = "mindlex-ai"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

pages_build_output_dir = ".open-next"

[assets]
binding = "STATIC_ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[ai]
binding = "AI"
